### ISSUE TITLE
Allow "expose" of the task list

### ISSUE THREAD

**Issue by savchenko** [djmitche/taskchampion#159]
### Summary

As synchronization between several clients is out-of-scope, perhaps adding `expose` command that allows to show current state of affairs can be helpful.

### Usage examples

- `ta expose tasks http 8080` exposes list of tasks on port 8080 via HTTP.

Initially, this can simply show the same output as `task list` without any formatting whatsoever. Essentially take stdout and pass it as the return body.

**Comment by djmitche** [comment]
What's the user story here?

Could this be better handled by a dedicated web-server app of some sort, that uses the Replica API?

**Comment by dbr** [comment]
I think if this is rephrased as some kind of (pluggable?) "export" command, the use cases become much more numerous:

1. Export all task to [other task management tool]
2. Export a subsets of my tasks for [project] to an HTML file so I can open and print it
3. Export a subset of tasks and serve the HTML over a temporary web server, to quickly share my "today" task list with a co-worker over LAN (this could possibly be done like `ta export html | theoretical-http-server-command-thing --file stdin --path /`
4. Export all tasks tagged with `notmyproblem` so someone else can use an equivalent `import` command to add the tasks to their list

In theory all of this could be done via the replica API but it becomes a much heavier thing to implement - especially as it mostly just replaces the "print to terminal" part of the CLI

**Comment by djmitche** [comment]
To be honest, those all sound like good external tools, rather than something baked into the CLI.  Maybe someone wants to export to iCalendar, so they write a `taskchampion-icalendar-export` tool that uses the Replica API to get access to all the tasks, and then writes them out.  We can talk separately about how to integrate such plugins (maybe we can make that available as `ta export icalendar` despite being a separate binary?), but to this particular issue I'm of the opinion that it's out of scope for core Taskchampion.

**Comment by savchenko** [comment]
> but to this particular issue I'm of the opinion that it's out of scope for core Taskchampion.

OK, closing and removing the milestone tag. Created https://github.com/djmitche/taskchampion/issues/173
